config/routes.rb
MLSApidoc::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  resources :static_pages

  resources :parameters

  resources :api_methods

  resources :api_lists

  devise_for :users
   
  resources :admin
  
  resources :home
  match "/methods/:id" => "api_methods#method_desc", :as=>:api_method_desc
  match "/download" => "home#downloads", :as=>:api_doc_download
  match "/download_file" => "home#download_file"
  match "/api_documentation"=>"home#api_doc",:as=>:api_doc
  match "/auth_documentations"=>"home#auth_doc",:as=>:auth_doc
  match "/error-codes"=>"home#error_code",:as=>:error_code
  match "/http-codes"=>"home#http_code",:as=>:http_code
  match "/getting-started"=>"home#getting_started",:as=>:getting_started
  match "/api/:id"=>"api_methods#new"
  match "/apimethods/:id"=>"api_methods#index"
  match "/api_destroy/:id"=>"api_lists#api_destroy",:as=>:api_destroy
  match "/apimethod_destroy/:id"=>"api_methods#apimethod_destroy",:as=>:apimethod_destroy
  match "/getting_started"=>"home#getting_started",:as=>:getting_started
  match "/delete/:id"=>"api_methods#delete_parameter",:as=>:delete_parameter
  match '/settings', :to => 'admin#settings'
  match '/update_settings', :to => 'admin#update_settings'
  match '/post_api_request', :to => 'api_methods#post_api_request'
  match '/put_api_request', :to => 'api_methods#put_api_request'
  match '/get_api_request', :to => 'api_methods#get_api_request'
  match '/delete_api_request', :to => 'api_methods#delete_api_request'

   root :to => "home#getting_started"

end

app/models/api_method.rb
class ApiMethod < ActiveRecord::Base
	has_many :parameters, :dependent => :destroy
	belongs_to :api_list
	#~ validates :name, :verb, :resource_url, :presence => true
  default_scope :order => 'position'
  scope :list_methods,lambda{|api_list_id| where('api_list_id=?',api_list_id).order('position')}
  scope :order_by_postion, order("position asc")
end

app/controllers/api_methods_controller.rb
class ApiMethodsController < ApplicationController
  # GET /api_methods
  # GET /api_methods.xml
  require 'httparty'
  before_filter :authenticate_user!, :except => ['method_desc']
  def index
    @api_methods = params[:id] ? ApiMethod.list_methods(params[:id]) : ApiMethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @api_methods }
    end
  end

  # GET /api_methods/1
  # GET /api_methods/1.xml
  def show
    @api_method = ApiMethod.find_by_id(params[:id])
    if request.xhr?
      render :partial => 'method_desc', :layout =>false
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @api_method }
      end
    end
  end

  # GET /api_methods/new
  # GET /api_methods/new.xml
  def new
    @list_id = params[:id] if params[:id]
    @api_method = ApiMethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @api_method }
    end
  end

  # GET /api_methods/1/edit
  def edit
    @api_method = ApiMethod.find_by_id(params[:id])
  end

  # POST /api_methods
  # POST /api_methods.xml
  def create
    @list_id = params[:id] if params[:id]
    @api_method = ApiMethod.new(params[:api_method])

    respond_to do |format|

      if @api_method.save
        @api_method.update_attributes(:api_list_id => params[:id])
        if params[:api_list]
          params[:api_list].each_with_index do |f, i|
            @parameter = Parameter.new
            @parameter.api_method_id = @api_method.id
            @parameter.name = params[:api_list]["parameter#{i.to_i+1}"]["name#{i.to_i+1}"]
            @parameter.description = params[:api_list]["parameter#{i.to_i+1}"]["description#{i.to_i+1}"]
            @parameter.validation = params[:api_list]["parameter#{i.to_i+1}"]["validation#{i.to_i+1}"]
            @error = params[:api_list]["parameter#{i.to_i+1}"]["request#{i.to_i+1}"] if params[:api_list]["parameter#{i.to_i+1}"]["request#{i.to_i+1}"]
            @parameter.is_request = params[:api_list]["parameter#{i.to_i+1}"]["request#{i.to_i+1}"] == "on" ? true : false
            @parameter.save
          end
        end
        format.html { redirect_to(@api_method, :notice => 'Api method was successfully created.') }
        format.xml  { render :xml => @api_method, :status => :created, :location => @api_method }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @api_method.errors, :status => :unprocessable_entity }
      end
    end
  end
  def delete_parameter
    @parameter = Parameter.find_by_id(params[:id])
    @parameter.destroy
    respond_to do |format|
      format.html { redirect_to(edit_api_method_path(@parameter.api_method)) }
      format.xml  { head :ok }
    end
  end

  # PUT /api_methods/1
  # PUT /api_methods/1.xml
  def update
    @api_method = ApiMethod.find_by_id(params[:id])
    respond_to do |format|
      if @api_method.update_attributes(params[:api_method])
        if params[:parameter]
          params[:parameter].each_with_index do |f, i|
            @parameter = Parameter.find_by_id(params[:parameter]["parameter#{i}"][:id])
            @parameter.update_attributes(:name => params[:parameter]["parameter#{i}"]["name#{i}"], :description => params[:parameter]["parameter#{i}"]["description#{i}"], :validation => params[:parameter]["parameter#{i}"]["validation#{i}"], :is_request => params[:parameter]["parameter#{i}"]["is_request#{i}"] == "1" ? true : false)
          end
        end
        if params[:api_list]
          params[:api_list].each_with_index do |f,i|
            @parameter = Parameter.new
            @parameter.api_method_id = @api_method.id
            @parameter.name = params[:api_list]["parameter#{i.to_i+1}"]["name#{i.to_i+1}"]
            @parameter.description = params[:api_list]["parameter#{i.to_i+1}"]["description#{i.to_i+1}"]
            @parameter.validation = params[:api_list]["parameter#{i.to_i+1}"]["validation#{i.to_i+1}"]
            @error = params[:api_list]["parameter#{i.to_i+1}"]["request#{i.to_i+1}"] if params[:api_list]["parameter#{i.to_i+1}"]["request#{i.to_i+1}"]
            @parameter.is_request = params[:api_list]["parameter#{i.to_i+1}"]["request#{i.to_i+1}"] == "on" ? true : false
            @parameter.save
          end
        end
        format.html { redirect_to(@api_method, :notice => 'Api method was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @api_method.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /api_methods/1
  # DELETE /api_methods/1.xml
  def destroy
    @api_method = ApiMethod.find_by_id(params[:id])
    @api_method.destroy

    respond_to do |format|
      format.html { redirect_to(api_methods_url) }
      format.xml  { head :ok }
    end
  end

  def method_desc
    @current_user = current_user
    @api = ApiList.order_by_postion
		@api_methods = ApiMethod.order_by_postion
    @api_method = ApiMethod.find_by_id(params[:id])
    @req_parameters = Parameter.params_list(params[:id],true)
    @res_parameters = Parameter.params_list(params[:id],false)
    #render :layout => false
  end

  def apimethod_destroy
    @api_list = ApiMethod.find_by_id(params[:id])
    @api_list.destroy
    respond_to do |format|
      format.html { redirect_to(api_methods_url) }
      format.xml  { head :ok }
    end
  end

  def post_api_request
    hash = ActiveSupport::JSON.decode(params['body'])
    response = HTTParty.post(params[:url], { :body => { :header => { :authentication_token => access_token } }.merge(hash) })
    result = JSON.parse(response.body)
    res = JSON.pretty_generate(result)
    if result['response'] == "success"
      render :json => { :response => res, :status => 'success' }
    elsif response['response'] == "failure"
      render :json => { :response => res, :status => 'failure' }
    else
      render :json => { :response => res, :status => 'success' }
    end
  end
  #~ HTTParty.put(form_url(__method__),{:body=>{:access_token=>access_token}.merge(params)}).parsed_response

  def put_api_request
    hash = ActiveSupport::JSON.decode(params['body'])
    response = HTTParty.put(params[:url], { :body => { :header => { :authentication_token => access_token } }.merge(hash) })
    result = JSON.parse(response.body)
    res = JSON.pretty_generate(result)
    if response['response'] == "success"
      render :json => { :response => res, :status => 'success' }
    elsif response['response'] == "failure"
      render :json => { :response => res, :status => 'failure' }
    else
      render :json => { :response => res, :status => 'success' }
    end
  end

  def get_api_request
    hash = ActiveSupport::JSON.decode(params['body'])
    response = HTTParty.get(params[:url], :body => { :header => { :authentication_token => access_token } })
    result = JSON.parse(response.body)
    res = JSON.pretty_generate(result)
    if response['response'] == "success"
      render :json => { :response => res, :status => 'success' }
    elsif response['response'] == "failure"
      render :json => { :response => res, :status => 'failure' }
    else
      render :json => { :response => res, :status => 'success' }
    end
  end

  def delete_api_request
    hash = ActiveSupport::JSON.decode(params['body'])
    response = HTTParty.delete(params[:url], :body => { :header => { :authentication_token => access_token } }).parsed_response
    res = JSON.pretty_generate(response)
    if response['response'] == "success"
      render :json => { :response => res, :status => 'success' }
    elsif response['response'] == "failure"
      render :json => { :response => res, :status => 'failure' }
    else
      render :json => { :response => res, :status => 'success' }
    end
  end

  private

  def access_token
    access_token  = params[:authentication_token]
  end


end

app/helpers/api_methods_helper.rb
module ApiMethodsHelper
  def method_lists(data)
    html_content = ""
    data.each do |method|
      html_content << "<tr>"
      html_content << "<td width='180px' style='font-size:16px;'>#{ method.name }</td>"
      html_content << "<td width='50px' style='font-size:12px;'>#{ link_to 'Show', method }</td>"
      html_content << "<td width='50px' style='font-size:12px;'>#{ link_to 'Edit', edit_api_method_path(method) }</td>"
      html_content << "<td width='50px' style='font-size:12px;'>#{ link_to 'Destroy', apimethod_destroy_path(method.id), :confirm => 'Are you sure?', :method => :delete }</td></tr>"
    end
    return html_content.html_safe
  end

  def api_method_show(api_data, api_methods_data)
    html_content = ""
    api_data.each do |api|
      html_content << "<div class='jq-portlet'><h5 class='apilist' id='api_#{api.id}' style='cursor:pointer;'>#{api.name}#{image_tag '/images/arrow-down.png', :id=>'arrow' }</h5><div class='jq-pBody' style='display: none;'><ul>"
      api_methods_data.each do |method|
        if method.api_list_id == api.id
          html_content << "<li id='jq-n-Downloading-jQuery'>#{ link_to_api_method(method) }</li>"
        end
      end
      html_content << "</ul></div></div>"
    end
    return html_content.html_safe
  end

  def api_method_params(data)
    html_content = ""
    data.parameters.each do |f|
      html_content << "<tr><td style='font-size:14px;'>#{ f.name }</td>"
      html_content << "<td style='font-size:14px;'>#{ f.description }</td>"
      html_content << "<td style='font-size:14px;'>#{ f.validation }</td>"
      html_content << "<td style='font-size:14px;'>#{ f.is_request }</td></tr>"
    end
    return html_content.html_safe
  end
end

app/views/api_methods/_form.html.erb
<script language="javascript">
  var intTextBox=0;
  var intTextBox1=0;
  function add() {
    intTextBox = intTextBox + 1;
    var parentelement = document.createElement("div");
    var foo = document.getElementById("fooBar");

    var child_element1 = document.createElement("input");
    var child_element2 = document.createElement("textarea");
    var child_element3 = document.createElement("textarea");
    var child_element4 = document.createElement("input");

    child_element1.setAttribute("type", "text");
    child_element2.setAttribute("rows", "3");
    child_element3.setAttribute("rows", "3");
    child_element4.setAttribute("type", "checkbox");

    parentelement.setAttribute("id", "element"+intTextBox);
    child_element1.setAttribute("id", "textbox_"+intTextBox);
    child_element2.setAttribute("id", "textarea_description_"+intTextBox);
    child_element3.setAttribute("id", "textarea_validation_"+intTextBox);
    child_element4.setAttribute("id", "checkbox_request_"+intTextBox);

    parentelement.setAttribute("name", "api_list[element"+intTextBox+"]");
    child_element2.setAttribute("name", "api_list[parameter"+intTextBox+"]"+"[description"+intTextBox+"]");
    child_element3.setAttribute("name", "api_list[parameter"+intTextBox+"]"+"[validation"+intTextBox+"]");
    child_element1.setAttribute("name", "api_list[parameter"+intTextBox+"]"+"[name"+intTextBox+"]");
    child_element4.setAttribute("name", "api_list[parameter"+intTextBox+"]"+"[request"+intTextBox+"]");

    parentelement.appendChild(child_element1);
    parentelement.appendChild(child_element2);
    parentelement.appendChild(child_element3);
    parentelement.appendChild(child_element4);
    foo.appendChild(parentelement);
  }

  function remove()
  {
    if(intTextBox != 0) {
      var contentID = document.getElementById("fooBar");
      contentID.removeChild(document.getElementById("element"+intTextBox));
      intTextBox = intTextBox-1;
    }
  }
</script>

<%= form_for(@api_method) do |f| %>
  <% if @api_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_method.errors.count, "error") %> prohibited this api_method from being saved:</h2>

      <ul>
        <% @api_method.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
  <%#= f.label :api_list_id %><br />
  <%#= f.text_field :api_list_id %>
  </div-->
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
  <%#= f.text_area :description,:rows=>8%>
    <%= tinymce_tag('api_method[description]', @api_method.description) %>
  </div>
  <div class="field">
    <%= f.label :resource_url %><br />
    <%= f.text_field :resource_url %>
  </div>
  <div class="field">
    <%= f.label :verb %><br />
    <%= f.text_field :verb %>
  </div>
  <div class="field">
    <%= f.label :request_url %><br />
    <%= f.text_field :request_url %>
  </div>
  <div class="field">
    <%= f.label :request_body %><br />
    <%= tinymce_tag('api_method[request_body]', @api_method.request_body) %>  </div>
  <div class="field">
    <div class="field">
      <%= f.label :notes %><br />
      <%= tinymce_tag('api_method[notes]', @api_method.notes) %>  </div>
    <div class="field">
      <%= f.label :success_response %><br />
  <%#= f.text_area :success_response,:rows=>8 %>
      <%= tinymce_tag('api_method[success_response]', @api_method.success_response) %>  </div>
    <div class="field">
      <%= f.label :error_responce %><br />
  <%#= f.text_area :error_response,:rows=>8 %>
      <%= tinymce_tag('api_method[error_response]', @api_method.error_response ) %>
    </div>

    <table>
      <tr>
        <th width="150px" style="font-size:12px;text-align:left;">Name</th>
        <th width="150px" style="font-size:12px;text-align:left;">Description</th>
        <th width="170px" style="font-size:12px;text-align:left;">Validation</th>
        <th width="150px" style="font-size:12px;text-align:left;">is Request?</th>
      </tr>
    </table>
    <div class="field">
      <% @api_method.parameters.each_with_index do |project,i| %>
        <%= f.fields_for :parameters, project do |project_fields| %>
          <%= project_fields.text_field :name,:name=>"parameter[parameter#{i}][name#{i}]" %>
          <%= project_fields.text_area :description,:name=>"parameter[parameter#{i}][description#{i}]",:rows=>3,:cols=>20 %>
          <%= project_fields.text_area :validation,:name=>"parameter[parameter#{i}][validation#{i}]",:rows=>3,:cols=>20  %>
          <%= project_fields.check_box :is_request,:name=>"parameter[parameter#{i}][is_request#{i}]"%>
          <%=project_fields.hidden_field :id,:name=>"parameter[parameter#{i}][id]",:value=>project.id%>
          <%=link_to "delete",delete_parameter_path(project.id)%>
        <% end %>
      <% end %>
    </div>
    <div align="right">
      <input type="button" value="Add" onclick="add()"/>
      <input type="button" value="remove" onclick="remove()"/>
    </div>
    <div id="fooBar"></div>
    <%=hidden_field_tag 'id', @list_id%>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/api_methods/_methods.html.erb
<div id="jq-interiorNavigation" style="width: 275px; min-height: 133.7em;">
<%#=link_to "Getting Started","#",:class=>"getting_started"%>
  <b><p width = "10px" style="height:20px;background-color:#788279;color:#D9E0F1;font-size:13px;text-align:center;padding-top:2px;margin :0 0 0.4em">API Methods</p></b>
  <%= api_method_show(@api, @api_methods) %>
</div>

app/views/api_methods/edit.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1>Editing api_method</h1>

  <%= render 'form' %>
  <p style="font-size:16px;">
    <%= link_to 'Show', @api_method %> |
    <%= link_to 'Back', api_methods_path %>
  </p>
</div>

app/views/api_methods/index.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1>Listing api_methods</h1>

  <table>
    <tr>
      <th style="font-size:16px;text-align:left;">Name</th>
    </tr>

    <%= method_lists(@api_methods) %>
  </table>

  <br />
  <p style="font-size:16px;">
    <%#= link_to 'New Api method', new_api_method_path %>
  </p>

app/views/api_methods/method_desc.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <%if !@api_method.nil?%>
    <h1 align="center">API Documentation</h1>
    <p><b style="font-size:18px;"><%=@api_method.api_list.name%></b></p>

    <p>
      <b style="font-size:16px;"><i> <%= @api_method.name %> </i></b><br/>

    </p>
    <%if @api_method.description.present?%>
      <p>
        <b>Description:</b><br/>
        <%= raw @api_method.description %>
      </p>

      <p>
        <b>Resource url:</b><br/>
        <%= @api_method.resource_url %><br/>
      </p>


      <p>
        <b>Verb:</b><br/>
        <%= @api_method.verb %>
      </p>
      <p>
        <%if !@req_parameters.blank?%>
          <b>Request parameter</b><br/>
        <table border=2 cellpadding="10px">
          <tr>
            <th width="100px" style="padding: 5px 8px 5px 5px;"><b>Name</b></th><th width="300px" style="padding: 5px 8px 5px 5px;"><b>Description</b></th>
            <th width="300px" style="padding: 5px 8px 5px 5px;"><b>Validation</b></th>
          </tr>
          <% @req_parameters.each do |param| %>
            <tr>
              <td width="100px" style="padding: 5px 8px 5px 5px;"><%= param.name%></td><td width="250px" style="padding: 5px 8px 5px 5px;"><%= param.description%></td>
              <td width="250px" style="padding: 5px 8px 5px 5px;"><%= param.validation%></td>
            </tr><%end%>	</table>
      <%end%><br/>
    </p>
    <p>
      <b>Request url:</b><br/>
      <%= @api_method.request_url %><br/>
      <% unless @current_user.nil?%>
        <%if @current_user.edit_enable == true %>
          <% if (@api_method.verb == "GET" || @api_method.verb == "get")%>
            <a href="javascript:void(0);" class="params_get">Edit</a>
            <br/>
          <div class="response params_get_val" style="display:none;">
            <form name="send_params" method="post" action="">
              <div style="font-size: 14px;">Method
                <select name="method" class="method">
                  <% if (@api_method.verb == "GET" ||  @api_method.verb == "get") %>
                    <option value="get" selected="selected">GET</option>
                  <% elsif (@api_method.verb == "DELETE" ||  @api_method.verb == "delete") %>
                    <option value="delete">DELETE</option>
                  <% end %>
                </select>
                <input type="hidden" name="access_tk" id="access_tk" value="<%= @current_user.access_token%>"/>
                <input type="text" name="url" class="url" value="<%= @current_user.api_url+@api_method.resource_url %>" style="margin: 0 0 0 10px;width: 519px;"/>
              </div><br/><br/>
              <div align="right" style="margin: 0 37px 0 0;">
                <img src="/images/loading.gif"  class="api_loader" style="margin: 0 10px;vertical-align: middle;display:none;" />
                <input type="submit" name="submit" value="Submit" class="params_submit"/>
                <input type="button" name="cancel" value="Cancel" class="cancel"/>
              </div>
              <br/><br/>
            </form>
          </div>
        <% end%>
      <% end%>
    <% end%>
    </p>
    <%if !@api_method.request_body.blank?%>
      <p>
        <b>Request body: </b><br/>
      <div class="response params" style="display:block;">
        <%=raw @api_method.request_body%>
      </div>
      <% unless @current_user.nil?%>
        <%if @current_user.edit_enable == true %>
          <% if (@api_method.verb == "POST" ||  @api_method.verb == "PUT" || @api_method.verb == "post"  ||  @api_method.verb == "put") %>
            <a href="javascript:void(0);" class="params_edit" style="float: right;margin: 10px 75px 0 0;">Edit</a>
            <div class="response params_update" style="display:none;">
              <form name="send_params" method="post" action="">
                <div style="font-size: 14px;">Method
                  <select name="method" class="method">
                    <% if (@api_method.verb == "POST" ||  @api_method.verb == "post") %>
                      <option value="post">POST</option>
                    <% elsif(@api_method.verb == "PUT"  ||  @api_method.verb == "put") %>
                      <option value="put">PUT</option>
                    <% end %>
                  </select>
                  <% if (@current_user.api_url.nil? || @current_user.api_url == '')
                    request_url = 'http://localhost:3000'
                  else
                    request_url = @current_user.api_url
                  end %>
                  <input type="hidden" name="access_tk" id="access_tk" value="<%= @current_user.access_token%>"/>
                  <input type="text" name="url" class="url" value="<%= request_url+@api_method.resource_url %>" style="margin: 0 0 0 10px;width: 519px;"/>
                </div>
                <textarea cols="80" rows="20" name="body" id="params_body" style="font-size: 14px; line-height: 20px;padding: 0;margin: 12px 0 0;">
                </textarea><br/><br/>
                <div align="right" style="margin: 0 37px 0 0;">
                  <img src="/images/loading.gif" class="api_loader" style="margin: 0 10px;vertical-align: middle;display:none;" />
                  <input type="submit" name="submit" value="Submit" class="params_submit"/>
                  <input type="button" name="cancel" value="Cancel" class="cancel"/><br/><br/>
                </div>
              </form>
            </div>
          <%end%>
        <%end%>
      <%end%>
      </p>
    <%end%>
    <p>
      <%if !@res_parameters.blank?%>

        <b>Response parameter</b><br/>
      <table border=2 style="padding: 5px 8px 5px 5px;">
        <tr>
          <th width="150px" style="padding: 5px 8px 5px 5px;"><b>Name</b></th>
          <th width="350px" style="padding: 5px 8px 5px 5px;"><b>Description</b></th>

        </tr>
        <% @res_parameters.each do |param| %>
          <tr>
            <td width="150px" style="padding: 5px 8px 5px 5px;"><%= param.name%></td><td width="350px" style="padding: 5px 8px 5px 5px;"><%= param.description%></td>

          </tr><%end%>	</table><%end%><br/>
    </p>
    <p>
      <b id="scroll_result">Success response:</b><br/>
    <div class="response success_res">
      <%= raw @api_method.success_response %>
    </div><br/>
    </p>
    <p>
      <b>Error response:</b><br/>
    <div class="response">
      <%= raw @api_method.error_response %>
    </div>
    <br/>
    </p>
  <%else%>
    <div id="jq-interior"><img src="/images/work_in_progress.png" height="400px" style="display: block;margin-left: auto;margin-right: auto"></div>
    <%end%>
  <%end%>
</div>

<script type="text/javascript">
  $('.params_edit').live('click',function(){
    $(".response.params_update").css({'display' : 'block'});
    $(".response.params").css({'display' : 'none'});
    $(".params_edit").css({'display' : 'none'});
    $("textarea#params_body").val($(".response.params").text());
  });
  $('.params_get').live('click',function(){
    $(".response.params_get_val").css({'display' : 'block'});
    $(".params_get").css({'display' : 'none'});
  });
  $('.cancel').live('click',function(){
    window.location.reload();
  });
  //~ test_api_request
  $('.params_submit').live('click',function(){
    access_token = $("#access_tk").val();
    api_url = $(".url").val();
    method = $(".method").val();
    $(".api_loader").show();
    switch(method)
    {
      case 'post':
        url_link = '/post_api_request'
        break;
      case 'put':
        url_link = '/put_api_request'
        break;
      case 'get':
        url_link = '/get_api_request'
        break;
      default:
        url_link = '/delete_api_request'
    }
    res = ''
    if($("#params_body").val()) {
      value = $("#params_body").val();
      res = value.replace(/\s+/g, '');
    }
    $.ajax({
      url : url_link,
      type: 'get',
      data: { body :	res, method : method, url : api_url, access_token : access_token },
      success:function(data){
        $(".response.success_res").html("<p style='font-size:13px; line-height:24px;'>"+data['response']+"</p>");
        if(data['status'] == "success") {
          if($(".response.success_res").hasClass("success")) {
            $(".response.success_res").removeClass("failure");
          } else {
            $(".response.success_res").removeClass("failure");
            $(".response.success_res").addClass(data['status']);
          }
        }else if(data['status'] == "failure") {
          if($(".response.success_res").hasClass("failure")) {
            $(".response.success_res").removeClass("success");
          } else {
            $(".response.success_res").removeClass("success");
            $(".response.success_res").addClass(data['status']);
          }
        }
        $(".api_loader").hide();
        goToByScroll("scroll_result");
      },
      error: function (request, status, error) {
        $(".response.success_res").text(request.responseText);
        $(".response.success_res").removeClass('success');
        $(".response.success_res").removeClass('failure');
        $(".api_loader").hide();
        goToByScroll("scroll_result");
      }
    });
    return false;
  });
		
  function goToByScroll(id){
    $('html,body').animate({scrollTop: $("#"+id).offset().top},'slow');
  }
</script>

app/views/api_methods/new.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1>New api_method</h1>
  <%= render 'form' %>
  <p style="font-size:16px;">
    <%= link_to 'Back', api_methods_path %>
  </p>
</div>

app/views/api_methods/show.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Api list:</b>
    <%= @api_method.api_list_id %>
  </p>

  <p>
    <b>Name:</b>
    <%= @api_method.name %>
  </p>

  <p>
    <b>Description:</b>
    <%= @api_method.description %>
  </p>

  <p>
    <b>Resource url:</b>
    <%= @api_method.resource_url %>
  </p>

  <p>
    <b>Verb:</b>
    <%= @api_method.verb %>
  </p>

  <p>
    <b>Request url:</b>
    <%= @api_method.request_url %>
  </p>
  <p>
    <b>Request body:</b>
    <%= @api_method.request_body %>
  </p>

  <p>
    <b>Success response:</b>
    <%=raw @api_method.success_response %>
  </p>

  <p>
    <b>Error response:</b>
    <%=raw @api_method.error_response %>
  </p>
  <p>Parameters</p>
  <p>
  <table>
    <tr><th width="180px" style="font-size:14px;text-align:left">Name</th>
      <th width="180px" style="font-size:14px;text-align:left">Description</th>
      <th width="180px" style="font-size:14px;text-align:left">Validation</th>
      <th width="180px" style="font-size:14px;text-align:left">is Request?</th></tr>
    <%= api_method_params(@api_method) %>
  </table>
</p>

<p style="font-size:16px;">
  <%= link_to 'Edit', edit_api_method_path(@api_method) %> |
  <%= link_to 'Back', api_methods_path %>
</p>
</div>