config/routes.rb
MLSApidoc::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  resources :static_pages

  resources :parameters

  resources :api_methods

  resources :api_lists

  devise_for :users
   
  resources :admin
  
  resources :home
  match "/methods/:id" => "api_methods#method_desc", :as=>:api_method_desc
  match "/download" => "home#downloads", :as=>:api_doc_download
  match "/download_file" => "home#download_file"
  match "/api_documentation"=>"home#api_doc",:as=>:api_doc
  match "/auth_documentations"=>"home#auth_doc",:as=>:auth_doc
  match "/error-codes"=>"home#error_code",:as=>:error_code
  match "/http-codes"=>"home#http_code",:as=>:http_code
  match "/getting-started"=>"home#getting_started",:as=>:getting_started
  match "/api/:id"=>"api_methods#new"
  match "/apimethods/:id"=>"api_methods#index"
  match "/api_destroy/:id"=>"api_lists#api_destroy",:as=>:api_destroy
  match "/apimethod_destroy/:id"=>"api_methods#apimethod_destroy",:as=>:apimethod_destroy
  match "/getting_started"=>"home#getting_started",:as=>:getting_started
  match "/delete/:id"=>"api_methods#delete_parameter",:as=>:delete_parameter
  match '/settings', :to => 'admin#settings'
  match '/update_settings', :to => 'admin#update_settings'
  match '/post_api_request', :to => 'api_methods#post_api_request'
  match '/put_api_request', :to => 'api_methods#put_api_request'
  match '/get_api_request', :to => 'api_methods#get_api_request'
  match '/delete_api_request', :to => 'api_methods#delete_api_request'

   root :to => "home#getting_started"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
	def api_doc
    @req_parameters = Parameter.params_list(@api_method.id,true)
    @res_parameters = Parameter.params_list(@api_method.id,false)
		#~ render :partial => "method_desc"
	end
	def auth_doc

	end
	def error_code
		@error = YAML.load_file("#{Rails.root.to_s}/config/error_code.yml")
	end
	def http_code

	end
	def getting_started
    #~ @api_method = ApiList.first.api_methods.first
    #~ if request.xhr?
    #~ render :partial => "getting_started"
    #~ else
    #~ @api_method = nil
    #~ @api = ApiList.find(:all,:order => 'position asc')
    #~ @api_methods = ApiMethod.find(:all,:order => 'position asc')
    #~ render "api_methods/method_desc"
		#~ end
	end
	def downloads
	end
	def download_file
		send_file "#{Rails.root}/public/#{params[:file_name]}", :disposition => 'attachment'
	end

end

app/helpers/home_helper.rb
module HomeHelper
  def api_methods_loop(api_data, api_methods_data)
    html_content = ""
    api_data.each do |api|
      html_content << "<div class='jq-portlet'><h5 class='apilist' id='api_#{api.id}'>#{api.name}#{image_tag '/images/arrow-down.png', :id=>'arrow' }</h5><div class='jq-pBody' style='display: none;'><ul>"
        api_methods_data.each do |method|
        if method.api_list_id == api.id
          html_content << "<li id='jq-n-Downloading-jQuery'>#{ link_to method.name, api_method_desc_path(method.id), :class=>"#{@api_method.id==method.id.to_s ? 'selected' : ''} method_def", :id=>'m_"+"#{method.id}'}</li>"
          end
      end
      html_content << "</ul></div></div>"
    end
    return html_content.html_safe
  end

  def home_error_codes(error_data)
    html_content = ""
    error_data.each do |type, errors|
      errors.each do |code, message|
        messages = message.split("%")
        html_content << "<tr><td>#{ code }</td>"
        html_content << "<td>#{ messages[0] }</td>"
        html_content << "<td>#{ messages[1] }</td></tr>"
      end
    end
    return html_content.html_safe
  end
end

app/views/home/_downloads.html.erb
<h1 class="page-title">Downloads</h1>
<br/>
<%=image_tag "/images/icon_bul.gif", :style=>"padding-left: 20px;"%>&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "API Documentation(v1.0)",download_file_path(:file_name=>'api_documentation.pdf')%><br/><br/>
<%=image_tag "/images/icon_bul.gif", :style=>"padding-left: 20px;"%>&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "Auth Documentation(v1.0)",download_file_path(:file_name=>'auth_documentation.pdf')%><br/><br/>

app/views/home/_getting_started.html.erb
<h1 class="page-title" style="font-size:16px;">Getting Started</h1>
<div style="float:left;margin-right:4%;padding-left:40px;">
  <p>This section describes in general terms the steps you need to take when you use the Spree API. Registering in Spree application is mandatory to use the REST APIs provided</p>
  <p>General procedure involved in using Spree API is very simple. Just follow the below steps.</p>
  <ul style="list-style: square outside none;margin-left:50px;">
    <li style="padding-bottom:7px;">Get the proper authorization. Do any necessary user login steps and OAuth authorization.</li>
    <li>Set up parameters. Decide which parameters you are passing to API and set their values or retrieve those values as input from the user of your application.
    <li>Build the request to the API. The request consists of the full URL to the API resource itself, plus the parameters and their values.
    <li>Make the request. You invoke each request with its appropriate HTTP method: GET, PUT, DELETE, or POST.
    <li>Get the response and parse it for the data you need. Some of the data may be contained directly within the response, marked by appropriate tags, and some data may appear in the form of links to other resources.
    <li>Use the response data to do further operations. You can use the links within a response to make other resource requests. For example, if you retrieve details about a item, the response includes URLs for categories of that item. You can use these URLs to access and display the categories.</li>
    <li>The Spree API will return the error code for the failed request or actions. Which helps the developers to know the exact reason for the failure.</li>
  </ul>
  <!--p>To know more about the API methods, visit <%#=link_to "API documentation",api_method_desc_path( @api_method) %>.</p-->
</div>

app/views/home/_temp_page.html.erb
<img src="/images/work_in_progress.png" height="400px" style="display: block;margin-left: auto;margin-right: auto">

app/views/home/api_doc.html.erb
<%=link_to "<< Back", "/"%>
<%= api_methods_loop(@api, @api_methods) %>
</div>
<div id="jq-primaryContent" style="width:850px; min-height: 133.7em;">
  <%=render :partial=>"method_desc"%>
</div>

<script>
  $(document).ready(function(){
    $('.apilist').click(function(){
      if($(this).siblings('.jq-pBody').css('display')=="none")
        $($(this).children('img')).attr('src','/images/arrow-up.png');
      else
        $($(this).children('img')).attr('src','/images/arrow-down.png');
      $(this).siblings('.jq-pBody').slideToggle('fast');
    });
    $('#api_<%=@api_method.api_list_id%>').click();
  });
</script>

app/views/home/auth_doc.html.erb
<%=render "temp_page"%>

app/views/home/downloads.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1 class="page-title" style="font-size:1.9em;text-align:center;">Downloads</h1>
  <br/>
  <div style="font-size:14px;">
    <%=image_tag "/images/icon_bul.gif", :style=>"padding-left: 20px;"%>&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "API Documentation(v1.0)",download_file_path(:file_name=>'api_documentation.pdf')%><br/><br/>
    <%=image_tag "/images/icon_bul.gif", :style=>"padding-left: 20px;"%>&nbsp;&nbsp;&nbsp;&nbsp;<%=link_to "Auth Documentation(v1.0)",download_file_path(:file_name=>'auth_documentation.pdf')%><br/><br/>
  </div>
</div>

app/views/home/error_code.html.erb
<style type="text/css">
  table.hovertable {
    font-family: verdana,arial,sans-serif;
    font-size:11px;
    color:#333333;
    border-width: 1px;
    border-color: #999999;
    border-collapse: collapse;
  }
  table.hovertable th {
    background-color:#c3dde0;
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #a9c6c9;
  }
  table.hovertable tr {
    background-color:#d4e3e5;
  }
  table.hovertable td {
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #a9c6c9;
  }
</style>
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1 class="page-title" style="font-size:16px;text-align:center;">Error Codes</h1>
  <p>&nbsp;</p>
  <table border=1 class="hovertable">
    <th style="width:200px;">Error Code</th>
    <th style="width:400px;"> Reason </th>
    <th style="width:400px;"> Message </th>
    <%= home_error_codes(@error) %>
  </table>
</div>

app/views/home/getting_started.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1 class="page-title" style="font-size:1.9em;text-align:center;">Getting Started</h1>
    <div style="float:left;margin-right:4%;padding-left:40px;">
    <h3>Introduction</h3>
    <p>This section describes in general terms, the steps you need to take when you use the Spree API. Registering in Spree application is mandatory to use the REST APIs provided</p>
    <h3>Process</h3>
    <p>General procedure involved in using Spree API is very simple. Just follow the below steps.</p>
    <ul style="list-style: square outside none;margin-left:50px;">
      <li style="padding-bottom:7px;">Get the proper authorization. Do any necessary user login steps and OAuth authorization.</li>
      <li>Set up parameters. Decide which parameters you are passing to API and set their values or retrieve those values as input from the user of your application.
      <li>Build the request to the API. The request consists of the full URL to the API resource itself, plus the parameters and their values.
      <li>Make the request. You invoke each request with its appropriate HTTP method: GET, PUT, DELETE, or POST.
      <li>Get the response and parse it for the data you need. Some of the data may be contained directly within the response, marked by appropriate tags, and some data may appear in the form of links to other resources.
      <li>Use the response data to do further operations. You can use the links within a response to make other resource requests. For example, if you retrieve details about a item, the response includes URLs for categories of that item. You can use these URLs to access and display the categories.</li>
      <li>The Spree API will return the error code for the failed request or actions. Which helps the developers to know the exact reason for the failure.</li>
  </ul>
  <!--p>To know more about the API methods, visit <%#=link_to "API documentation",api_method_desc_path( @api_method) %>.</p-->
  <div>
    <h3>Response Format</h3>
    <p>The response returned by the provider can be in either <b>JSON</b> or <b>XML</b>. Each format specifies a way of encoding name-value pairs which comprise the response data. Each format has an associated mime-type which must be returned in the Content-type header along with the response.</p>
  </div>
    <div>
    <h3>Request Format</h3>
    <p>Access tokens are similar to session tokens. Authorization can be performed with an access token that is submitted with every secure request. Make sure that the Access token is stored securely and make every request with the access token. For every GET request access_token is sent as an extra parameter. And for other request token is embedded with the request body.</p>
  </div>
  </div>
</div>

app/views/home/http_code.html.erb
<div id="jq-primaryContent" style="width:867px; min-height: 133.7em;">
  <h1 class="page-title" style="font-size:16px;text-align:center;">Http Codes</h1>
  <%=render "temp_page"%>
</div>

app/views/home/index.html.erb
<div id="jq-primaryContent" style="width:1172px; min-height:46em;">
  <div id="jq-interior">
    <div style="float:left;width:48%;margin-right:4%;">
      <h3><%=link_to "Getting Started","/getting_started",:style=>"font-size :16px;"%></h2>
      <p>A secure platform that allows you to capture content in meetings and share it securely with colleagues</p>
      <p>Analyze key metrics related to your meetings</p>
      <p>Create private distribution lists and share content with targeted team members</p>
      <p>Monitor meeting topics and track followup action items</p>
      <p>Provide a variety of templates that allow you to capture content based on your job function</p>
      <h3><%=link_to "Authentication Documentation",auth_doc_path,:style=>"font-size :16px;"%></h2>
			      <p>  This document is for application developers to authenticate/authorize their request with Spree. Spree allows access to the protected data only for the authorized users.</p>
      <p>The authentication might be token based for the Spree applications and oAuth for the other applications. This enables third-party developers to build applications that can fetch data on behalf of Spree users without the need to first obtain their usernames and passwords.</p>
     
    </div>
    <div style="float:left;width:48%;">
     <h3><%=link_to "API Documentation",link_to_method,:style=>"font-size :16px"%></h2>
 <p> This document is written for application developers using the Spree Data APIs to access a user's data. This enables third-party developers to build applications that can fetch data on behalf of Spree users.</p>
      <p>This document explains the basic functionalities of the API methods to access the protected resource. You can find here all the methods available in Spree API. To know more jump right into the API resource documentation. Before using the Spree API you need to do register in Spree.</p>
      <p></p>
      <h3><%=link_to "Error Codes",error_code_path,:style=>"font-size :16px;"%></h2>
      <p>Spree API will return the error code for the failed request or actions. Which helps the developers to know the exact reason for the failure.</p> 
      <h3><%=link_to "Http Codes",http_code_path,:style=>"font-size :16px;"%></h2>
      <p>The Spree REST APIs use the HTTP protocol for sending and retrieving data. Client code utilizing the REST APIs make an HTTP request to the Spree Service provider and process the HTTP response accordingly. Included with the HTTP response data is the HTTP response code. The response code gives the client some indication as to the success of the HTTP request, and can provide information on how the client should handle the included response data. Please follow the above link to know more about the HTTP status.</p>
    </div>
  </div>
</div>